### PR TITLE
consistent menu presences

### PR DESCRIPTION
**Pull request by janinhasz**
competitive lobbies should now show rank throughout queue/pregame states and when away instead of only when idle (plus I think it looks overall nicer)

### CODE REVIEW

**Comment by janinhasz** [comment]
when you had "show_rank_in_lobby" on false it crashed directly, found a lazy fix for it which works fine

**Comment by colinhartigan** [comment]
will look for a better way to implement this (i dont like each presence having an if/else just for this one setting), but i like the idea

**Comment by janinhasz** [comment]
should i just edit them to just have the other changes ive made then? you can fix on top of that ig

**Comment by janinhasz** [comment]
reverted the fix, it just has the consistency edits now

**Comment by janinhasz** [comment]
closed to be remade another time

**Pull request closed without merging**
